import React, {useState} from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const bookingUrl='https://www.picktime.com/book/6952be59-8374-4124-b1a2-b0c6a9140f96';
const rateUsUrl='https://www.google.com/search?q=Body+%26+Energy+Spa+Massage+Center';
const qr=(url,size=300)=>`https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(url)}`;

function App(){
 const [lang,setLang]=useState('en');
 const t={
  en:{nav:['About','Services','Experience','Contact'],heroSmall:'Luxury Wellness & Massage',heroTitle:'Relax your body. Restore your energy.',heroText:'Professional massage therapies and body care treatments in a calm, elegant and welcoming massage center environment.',book:'Book Appointment',view:'View Services',aboutSmall:'About Body & Energy Massage Center',aboutTitle:'A place made for calmness, care and renewal.',about1:'At Body & Energy Massage Center, every treatment is designed to help you relax, release tension and reconnect with your body.',about2:'Our team offers professional massage therapies, body care treatments and personalized wellness experiences in a peaceful massage center atmosphere.',about3:'Whether you need relaxation, muscle relief or a premium self-care experience, we welcome you with care, professionalism and positive energy.',catSmall:'Our Treatment Categories',catTitle:'Explore our massage experiences',catText:'Start by choosing the type of treatment that matches your body, your mood and your needs.',popular:'Most Popular',popularTitle:'Guest favourite treatments',hours:'Opening Hours',hoursText:'Scan to book online or contact us directly.',contact:'Contact',contactTitle:'Book your wellness experience',send:'Send a Message',name:'Your Name',phone:'Phone Number',message:'Your Message',button:'Send Message',rights:'All rights reserved.'},
  el:{nav:['Σχετικά','Υπηρεσίες','Εμπειρία','Επικοινωνία'],heroSmall:'Luxury Wellness & Massage',heroTitle:'Χαλάρωσε το σώμα σου. Γέμισε ξανά ενέργεια.',heroText:'Επαγγελματικές θεραπείες μασάζ και περιποίησης σώματος σε έναν ήρεμο, κομψό και φιλόξενο χώρο μασάζ.',book:'Κλείστε Ραντεβού',view:'Δείτε Υπηρεσίες',aboutSmall:'Σχετικά με το Body & Energy Massage Center',aboutTitle:'Ένας χώρος για ηρεμία, φροντίδα και ανανέωση.',about1:'Στο Body & Energy Massage Center, κάθε θεραπεία είναι σχεδιασμένη για να σας βοηθήσει να χαλαρώσετε, να αποβάλετε την ένταση και να νιώσετε ξανά το σώμα σας.',about2:'Η ομάδα μας προσφέρει επαγγελματικές θεραπείες μασάζ, περιποίησης σώματος και προσωποποιημένες εμπειρίες ευεξίας σε ήρεμη ατμόσφαιρα μασάζ.',about3:'Είτε χρειάζεστε χαλάρωση, ανακούφιση μυών ή μια premium εμπειρία φροντίδας, σας υποδεχόμαστε με επαγγελματισμό και θετική ενέργεια.',catSmall:'Κατηγορίες Θεραπειών',catTitle:'Ανακαλύψτε τις εμπειρίες μασάζ που προσφέρουμε',catText:'Ξεκινήστε επιλέγοντας την κατηγορία θεραπείας που ταιριάζει στο σώμα, τη διάθεση και τις ανάγκες σας.',popular:'Most Popular',popularTitle:'Οι πιο δημοφιλείς θεραπείες',hours:'Ωράριο Λειτουργίας',hoursText:'Σκανάρετε για online κράτηση ή επικοινωνήστε απευθείας μαζί μας.',contact:'Επικοινωνία',contactTitle:'Κλείστε την εμπειρία ευεξίας σας',send:'Στείλτε Μήνυμα',name:'Το όνομά σας',phone:'Τηλέφωνο',message:'Το μήνυμά σας',button:'Αποστολή Μηνύματος',rights:'Με επιφύλαξη παντός δικαιώματος.'},
  de:{nav:['Über uns','Leistungen','Erlebnis','Kontakt'],heroSmall:'Luxury Wellness & Massage',heroTitle:'Entspannen Sie Ihren Körper. Erneuern Sie Ihre Energie.',heroText:'Professionelle Massagetherapien und Körperpflegebehandlungen in einer ruhigen, eleganten Massage-Center-Atmosphäre.',book:'Termin buchen',view:'Leistungen ansehen',aboutSmall:'Über Body & Energy Massage Center',aboutTitle:'Ein Ort für Ruhe, Pflege und Erneuerung.',about1:'Bei Body & Energy Massage Center ist jede Behandlung darauf ausgerichtet, Ihnen Entspannung, Muskelentlastung und neues Körpergefühl zu schenken.',about2:'Unser Team bietet professionelle Massagen, Körperpflegebehandlungen und persönliche Wellness-Erlebnisse.',about3:'Ob Entspannung, Muskelentlastung oder ein Premium-Erlebnis – wir begrüßen Sie mit Professionalität und positiver Energie.',catSmall:'Behandlungskategorien',catTitle:'Entdecken Sie unsere Massage-Erlebnisse',catText:'Wählen Sie zuerst die Kategorie, die zu Ihrem Körper und Ihren Bedürfnissen passt.',popular:'Most Popular',popularTitle:'Beliebte Behandlungen',hours:'Öffnungszeiten',hoursText:'Scannen Sie den QR-Code zur Online-Buchung oder kontaktieren Sie uns direkt.',contact:'Kontakt',contactTitle:'Buchen Sie Ihr Wellness-Erlebnis',send:'Nachricht senden',name:'Ihr Name',phone:'Telefonnummer',message:'Ihre Nachricht',button:'Nachricht senden',rights:'Alle Rechte vorbehalten.'}
 }[lang];
 const categories={en:[['Relaxing Massages','Gentle and calming treatments for stress relief, relaxation and inner balance.',['Swedish Massage','Aromatherapy Massage','Body & Energy Special']],['Therapeutic Massages','Focused treatments for muscle tension, stiffness, recovery and body relief.',['Deep Tissue Massage','Hippocrates Full Body','Hippocrates Back & Neck','Sport Massage']],['Eastern Rituals','Rituals inspired by traditional Asian and Hawaiian techniques.',['Thai Massage','Balinese Massage','Lomi Lomi Massage','Huna Mana']],['Body & Face Care','Face and body treatments designed to renew, hydrate and refresh the skin.',['Body Scrub + Hydration','Express Face Care','Exclusive Masks','Exclusive Treatments']]],el:[['Χαλαρωτικά Μασάζ','Ήπιες και χαλαρωτικές θεραπείες για μείωση στρες, ηρεμία και ισορροπία.',['Swedish Massage','Aromatherapy Massage','Body & Energy Special']],['Θεραπευτικά Μασάζ','Στοχευμένες θεραπείες για μυϊκή ένταση, δυσκαμψία και ανακούφιση.',['Deep Tissue Massage','Hippocrates Full Body','Hippocrates Back & Neck','Sport Massage']],['Eastern Rituals','Τελετουργικές θεραπείες εμπνευσμένες από ασιατικές και χαβανέζικες τεχνικές.',['Thai Massage','Balinese Massage','Lomi Lomi Massage','Huna Mana']],['Body & Face Care','Θεραπείες προσώπου και σώματος για ανανέωση και ενυδάτωση.',['Body Scrub + Hydration','Express Face Care','Exclusive Masks','Exclusive Treatments']]],de:[['Entspannungsmassagen','Sanfte Behandlungen für Stressabbau, Entspannung und innere Balance.',['Swedish Massage','Aromatherapy Massage','Body & Energy Special']],['Therapeutische Massagen','Gezielte Behandlungen für Muskelverspannungen und Regeneration.',['Deep Tissue Massage','Hippocrates Full Body','Hippocrates Back & Neck','Sport Massage']],['Eastern Rituals','Rituale inspiriert von asiatischen und hawaiianischen Techniken.',['Thai Massage','Balinese Massage','Lomi Lomi Massage','Huna Mana']],['Body & Face Care','Gesichts- und Körperbehandlungen zur Erneuerung und Hydration.',['Body Scrub + Hydration','Express Face Care','Exclusive Masks','Exclusive Treatments']]]}[lang];
 const pics=['https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1200&auto=format&fit=crop','https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1200&auto=format&fit=crop','https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1200&auto=format&fit=crop','https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=1200&auto=format&fit=crop'];
 const popular=[['Hippocrates Full Body Massage','60 min','80€'],['Sport Massage','45 min','75€'],['Balinese Massage','60 min','90€'],['Aromatherapy Massage','60 min','85€']];
 return <div><div className="top"><span>Body & Energy Massage Center</span><span>Tel: +30 6944372227 · 10:00 – 18:00</span></div><header><div className="brand"><img src="/logo.jpg"/><b>BODY & ENERGY MASSAGE CENTER</b></div><nav>{t.nav.map((n,i)=><a key={n} href={['#about','#services','#experience','#contact'][i]}>{n}</a>)}<button onClick={()=>setLang('en')}>🇬🇧</button><button onClick={()=>setLang('el')}>🇬🇷</button><button onClick={()=>setLang('de')}>🇩🇪</button></nav></header><section className="hero"><div className="heroInner"><p className="gold">{t.heroSmall}</p><h1>{t.heroTitle}</h1><p>{t.heroText}</p><button onClick={()=>window.open(bookingUrl,'_blank')}>{t.book}</button><a className="outline" href="#services">{t.view}</a></div></section><section id="about" className="split"><div><p className="gold">{t.aboutSmall}</p><h2>{t.aboutTitle}</h2><p>{t.about1}</p><p>{t.about2}</p><p>{t.about3}</p></div><div className="photos"><img src={pics[3]}/><img src={pics[0]}/></div></section><section id="services"><div className="center"><p className="gold">{t.catSmall}</p><h2>{t.catTitle}</h2><p>{t.catText}</p></div><div className="cards">{categories.map((c,i)=><div className="card" key={c[0]}><img src={pics[i]}/><h3>{c[0]}</h3><p>{c[1]}</p><ul>{c[2].map(x=><li key={x}>✦ {x}</li>)}</ul></div>)}</div><div className="popular"><p className="gold">{t.popular}</p><h2>{t.popularTitle}</h2><div className="popgrid">{popular.map(p=><div className="pop" key={p[0]}><h3>{p[0]}</h3><span>{p[1]}</span><b>{p[2]}</b></div>)}</div></div></section><section id="experience" className="experience"><div className="exp"><img src={pics[3]}/><h3>{t.experienceTitle1}</h3><p>{t.experienceText1}</p></div><div className="exp"><img src={pics[1]}/><h3>{t.experienceTitle2}</h3><p>{t.experienceText2}</p></div><div className="exp"><img src={pics[0]}/><h3>{t.experienceTitle3}</h3><p>{t.experienceText3}</p></div></section><section className="hours"><h2>{t.hours}</h2><h3>10:00 – 18:00</h3><p>{t.hoursText}</p><img src={qr(bookingUrl,400)}/></section><section id="contact" className="split contact"><div><p className="gold">{t.contact}</p><h2>{t.contactTitle}</h2><p>📞 Tel: +30 6944372227</p><p>💬 WhatsApp & Viber Available</p><p>📍 Greece</p><p>🕙 10:00 – 18:00</p></div><div className="form"><h3>{t.send}</h3><input placeholder={t.name}/><input placeholder={t.phone}/><textarea placeholder={t.message}></textarea><button>{t.button}</button></div></section><footer><div><h3>Rate Us</h3><img src={qr(rateUsUrl,300)}/></div><img className="flogo" src="/logo.jpg"/><p>© Body & Energy Massage Center. {t.rights}</p></footer></div>
}

createRoot(document.getElementById('root')).render(<App/>);
